language: node_js
cache: npm
node_js:
  - 8
  - 10
  - 11
  - 12

before_deploy: npm run prepublishOnly
deploy:
  provider: npm
  email: andreas@stassi.net
  api_key:
    secure: AqpE8eZZDnBO5gSbxOQ0QR6eKtD1r9NjjJtiYv2302u6/2J/lAcyl/ugQu2oJXKh4HgzYWzWTzQZSdKky0EwqhTWe4weciZApkUiyhAf9vTqn58yHd894to5NGwfikFXks5mvvpcsuVjFMBI+xed6ydZkfrzcItk20SDtuOccxCAnIn8+5iSNxXPvx3by0z3UXHeu7ncZZS9TVpHw10AIL4Wun8U6Nw+ZXhcr/OgOVM5L9srro8fIpg6XIoPedTieKqYZCnbSPxxEKoPYbgPWCSAdN0nvIhE12FiSqv1EgByq29axetfMAdzsz6p62XxTHYZkLZKZQQKQpYP0BIH/ZwddFkPUB323zOgamsfRHi5qTDIL/bJdXWfITpaU3WtL7ZBhf1fQuBv14oH93ill2vU9cPUSCAEPGoNHihTtdRCm0jVp+WFa3HNVgNAaY2cXW09v5lPcwvg4B03kk5XbiidVvr1WC3aSudRxO9e76IAbZwbmSTRJyZIt6Mn8k7HNerGhu9W+YjuaDH08H3yV9rFyAL5YbSR3779onCa2KOM+bidrnuvLVlj6W/PjliJEBXr1iaOAENBrVU8VI6WwngrSkuIyxJxUEyUXSRi1MT+uXSO+o7s81Li+XNSgmk59p4wYFvkqtivGoe+Ju6YWlu5TAE/jmryC/iowdbeUI4=
  skip_cleanup: true
  on:
    node: 12
